version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: todo-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - todo-net

  backend:
    build:
      context: ./server   # путь к папке с backend (Spring Boot)
      dockerfile: Dockerfile
    container_name: todo-backend
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/todo
      SPRING_DATASOURCE_USERNAME: todo
      SPRING_DATASOURCE_PASSWORD: todo
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - todo-net

  frontend:
    build:
      context: ./client   # путь к папке с frontend (React/Vite)
      dockerfile: Dockerfile
    container_name: todo-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - todo-net

volumes:
  db_data:

networks:
  todo-net:
