version: '3.8'

services:
  planicore:
    build: .
    container_name: planicore
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xms512m -Xmx1024m
    restart: on-failure
    networks:
      - app-network

networks:
  app-network:
    driver: bridge